#!/usr/bin/env bash

#Exit the script if any individual command fails
set -o errexit

#Exit the script if it tries to use any undeclared variables
set -o nounset

#Un-comment this next line if you want to see exactly what this script is doing
set -o xtrace


function printUsage {
    echo "COMMAND: cconf - appends something content-record config.yaml's table names"
    echo "USAGE: cconf <target config file> <optional replacement text>"
}

if [[ $# -lt 1 ]]
    then printUsage
        exit 1
    else
        fileName="${1}"
        if [[ $# != 1 ]]
            then
                appendText="${2}"
            else
                appendText="MAC"
        fi
fi

sed -i "s/refrecord_nomenclature_v2/${appendText}_refrecord_nomenclature_v2/g" "${fileName}"
sed -i "s/refrecord_content_meta_v2/${appendText}_refrecord_content_meta_v2/g" "${fileName}"
sed -i "s/refrecord_content_npi_v2/${appendText}_refrecord_content_npi_v2/g" "${fileName}"

