#!/usr/bin/env bash

#Exit the script if any individual command fails
set -o errexit

#Exit the script if it tries to use any undeclared variables
set -o nounset

#Un-comment this next line if you want to see exactly what this script is doing
#set -o xtrace


function printUsage {
    echo "COMMAND: checkspace - Lists the folders in the current directory and how big they are"
    echo "USAGE: checkspace"
}

if [[ $# != 0 ]]
	then printUsage
		exit 1
	else
	echo "FILESYSTEM STATS :"
	df -h
	echo "CURRENT DIRECTORY STATS: "
	sudo du -smc * | sort -n
fi