#!/usr/bin/env bash

#Exit the script if any individual command fails
set -o errexit

#Exit the script if it tries to use any undeclared variables
set -o nounset

#Un-comment this next line if you want to see exactly what this script is doing
#set -o xtrace

function printUsage {
    echo "COMMAND: copyfromlocal - attempts to copy a file from the local filesystem into your home directory on HDFS"
    echo "USAGE: copyfromlocal <local file>"
}

if [[ $# != 1 ]]
	then printUsage
		exit 1
	else
        hadoop fs -copyFromLocal "${1}" "hdfs:///user/$USER/"
fi