#!/usr/bin/env bash

#Exit the script if any individual command fails
set -o errexit

#Un-comment this next line if you want to see exactly what this script is doing
#set -o xtrace

function printUsage {
    echo "COMMAND: . hcp - Adds a jar in the current folder to the hadoop classpath."
    echo "USAGE: . hcp <jar name>"
    echo "NOTE: This command MUST be run with a \".\" preceding it. Otherwise, it will seem to have no effect."
}

if [[ $# != 1 ]]
	then printUsage
	else
    	echo "NOTE: This command MUST be run with a \".\" preceding it. Otherwise, it will seem to have no effect."
        currentDirectory=$(pwd)
        currentHadoopClasspath=$(echo "$HADOOP_CLASSPATH")
        echo "previou classpath: ${currentHadoopClasspath}"
        export HADOOP_CLASSPATH="${currentHadoopClasspath}:${currentDirectory}"'/'"${1}"
        newClasspath=$(echo "$HADOOP_CLASSPATH")
        echo "current classpath: ${newClasspath} "
fi