#!/usr/bin/env bash

#Exit the script if any individual command fails
set -o errexit

#Un-comment this next line if you want to see exactly what this script is doing
#set -o xtrace

function printUsage {
    echo "COMMAND: . hcp"
    echo "USAGE: . hcp <jar name>"
    echo "NOTE: This command MUST be run with a \".\" preceding it. Otherwise, it will seem to have no effect."
}

if [[ $# != 1 ]]
	then printUsage
	else
    	echo "NOTE: This command MUST be run with a \".\" preceding it. Otherwise, it will seem to have no effect."
        currentDirectory=$(pwd)
        currentHadoopClasspath=$(echo "$HADOOP_CLASSPATH")
        echo "current classpath: ${currentHadoopClasspath}"
        export HADOOP_CLASSPATH="${currentHadoopClasspath}:${currentDirectory}"'/'"$1"
        newClasspath=$(echo "$HADOOP_CLASSPATH")
        echo "classpath is now : ${newClasspath} "
fi