#!/usr/bin/env bash

#Exit the script if any individual command fails
set -o errexit

#Exit the script if it tries to use any undeclared variables
set -o nounset

#Un-comment this next line if you want to see exactly what this script is doing
#set -o xtrace

function printUsage {
    echo "COMMAND: rechup - Runs a jar with hadoop and a bunch of extra options. Output is directed to file."
    echo "USAGE: rechup <jar name> \"<command and parameters in quotes>\" <output file name>"
}

if [[ $# != 3 ]]
	then printUsage
		exit 1
	else
        currentDirectory=$(pwd)
        export HADOOP_CLIENT_OPTS='-XX:MaxPermSize=512m'
        export HADOOP_CLASSPATH="$currentDirectory"'/'"$1"
        childOpts="-Xmx6144m -Xms1536M -Xss1M -XX:MaxPermSize=700M"
        nohup hadoop jar "$1" -D mapred.child.java.opts="${childOpts}" -D mapred.map.java.opts="${childOpts}" -D mapred.reduce.java.opts="${childOpts}" -D mapred.job.map.memory.mb=8000 -D mapred.job.reduce.memory.mb=8000 "$2" 2> "$3" 1> "$3" &
fi