#!/usr/bin/env bash

#Exit the script if any individual command fails
set -o errexit

#Exit the script if it tries to use any undeclared variables
set -o nounset

#Un-comment this next line if you want to see exactly what this script is doing
#set -o xtrace

echo "COMMAND: runjar"
echo "USAGE: runjar <jar name> <whatever else>"


currentDirectory=$(pwd)
jarname=$1
shift
export HADOOP_CLIENT_OPTS='-XX:MaxPermSize=512m'
export HADOOP_CLASSPATH="${currentDirectory}"'/'"${jarname}"
hadoop jar ${jarname} -D mapred.child.java.opts="-Xmx6144m -Xms1536M -Xss1M -XX:MaxPermSize=700M" -D mapred.job.map.memory.mb=8000 -D mapred.job.reduce.memory.mb=8000 "$@"
