#!/usr/bin/env bash

#Exit the script if any individual command fails
set -o errexit

#Exit the script if it tries to use any undeclared variables
set -o nounset

#Un-comment this next line if you want to see exactly what this script is doing
set -o xtrace

function printUsage {
    echo "COMMAND: runjar - Runs a jar with hadoop and a bunch of extra options."
    echo "USAGE: runjar <jar name> <whatever else, but don't use quotes>"
}

if [[ $# -lt 1 ]]
	then printUsage
		exit 1
	else
        currentDirectory=$(pwd)
        jarname=$1
        shift
        export HADOOP_CLIENT_OPTS="-XX:MaxPermSize=512m -Dhttps.protocols=TLSv1"
        export HADOOP_CLASSPATH="${currentDirectory}"/"${jarname}"
        childOpts="-Xmx6144m -Xms1536M -Xss1M -XX:MaxPermSize=700M"
        #The first argument in childOpts needs to be ~2gb less than mapred.job.map.memory.mb and mapred.job.reduce.memory.mb
        hadoop jar "${jarname}" -D mapred.child.java.opts="${childOpts}" -D mapred.map.java.opts="${childOpts}" -D mapred.reduce.java.opts="${childOpts}" -D mapred.job.map.memory.mb=8000 -D mapred.job.reduce.memory.mb=8000 -D hbase.rpc.timeout=1000000 -D hbase.regionserver.lease.period=1000000 -D mapred.task.timeout=1800000 $@
fi